name: Build static libraries

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebp-dev libcurl4-openssl-dev libboost-system-dev libsqlite3-dev sqlite3

      - name: Configure and Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DGERUEST_ENABLE_SQLITE=ON
          cmake --build . --config Release

      - name: Build Unit Tests
        run: |
          cd src/unitTests
          mkdir -p build && cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DGERUEST_ENABLE_SQLITE=ON
          cmake --build .

      - name: Run Unit Tests
        run: |
          cd src/unitTests/build
          ctest --output-on-failure --verbose
